### ISSUE TITLE
fcs experiment TODO

### ISSUE THREAD

**Issue by atruskie** [QutEcoacoustics/interaction-experiments#1]
- [x] fix experiment menu at `experiments/`
- [x] cleanup experiment template (hide title, text, move dates to bottom)
- [x] neaten ethics (left-align, semantics, etc)
- [x] larger default font size
- [x] help @KellieVella implement the survey
   - either as a series of timeline steps
   - or as another plugin that can load an HTML page (like the one already implemented), and store the result of the form in data. Example implementation:  
      - https://github.com/jspsych/jsPsych/blob/40d50e89a20bd0b0677be4d64999fac9b429690a/plugins/jspsych-survey-html-form.js
     - a better option, this one lets us keep the form in markdown: https://github.com/jspsych/jsPsych/blob/40d50e89a20bd0b0677be4d64999fac9b429690a/plugins/jspsych-survey-html-form.js
- for the `annotate-image-audio` image plugin
  - [x] remove the volume UI from the media player
  - [x] remove the `<table>` layout from the `annotate-image-audio` plugin
  - [x] fix other layout issues in `annotate-image-audio` plugin
  - [x] in `data` add a section for _removed_ annotations
  - [x] remove annotorious _Click and Drag to Annotate_ UI prompt
  - [x] add "externalHtmlPerhamble" option to insert instructions above annotation area 
  - [x] annotorious canvas should scale with image resize
  - [x] annotorious bug where sometimes the canvas width and height is 0
  - [x] annotorious bug "cannot read property 'style' of null" - might be the same as above, prevents drawing
  - [x] high priority: add axes around image (d3 axes plugin should work well)
  - [x] high priority: plugin needs to unbind event handler after trial (or a closure is inappropriately captured). It seems annotations are added to the data from every previous use of the plugin.
- [x] track extra metadata during the experiment
  1. [x] time spent listening to audio
  2. [x] media-interaction log  (even type {play, pause, seek}, time index, timestamp)
  3. [ ] ~~click map (element id, x, y, timestamp)~~
  4. [x] Ensure interaction data is exported `jsPsych.data.getInteractionData()`
- [x] setup submit lambda (talk to @atruskie)
  - [x] generate unique id for data (`jsPsych.randomization.randomID(length)`
  - [x] support multiple submit of data (minimum: after experimental task, and at end;  optional: also after IMI survey)
- [x] figure out why css isn't updating/being cached
- [x] make magic happen i.e. draw all preamble text from one md file (Tutorial)
- [x] annotate field slips behind the audio bar when low on the visualisation and blocks entering 'save' or 'cancel' button - possible fix: put the annotation field above the box
- [x] need to validate form inputs (where appropriate)
- [x] upload audio
- [ ] ~~add "width-only" option that locks annotations vertical bounds to top and bottom~~
- [x] disable continue button until tutorial instructions looked at
- [x] make audio bar lock to image and align times (playing and dragging changes the starting point & resizing the screen smaller or larger changes the end point)
- [x] check production submit
- [x] add a vertical line that tracks with the audio button
- [x] make compatible with range of browsers (after pilot)
- [x] get likert scales that appear at end of experiment (randomSurveys) same width as the likert scales that appear earlier 
- [ ] ~~low priority: dropdown option instead of textual tagging~~
**Updated with new additional tasks**

**Comment by atruskie** [comment]
CSS caching bug fixed in f612d671c1f9b26fea35e388bb1475d95712c7cd

**Comment by atruskie** [comment]
- slideable magic instructions completed in 87a8ca0ee6989cb3ee78cd82492320415b6da0b3
- lager default font-size: f2bbbd310f7aba6145391d83896b5c2b10275fd5

**Comment by atruskie** [comment]
- annotorious repeat use bugs fixed in f6ced2892180432be4e1c02342357586e169525a

**Comment by atruskie** [comment]
- submission completed in 33e85c5c9f3c69cbd1c378a9d96d53b84fd80ff4 and d3001cbc7da59c522a0b04c7ee3c4a4d24ba8a75
- interaction data in 227ccb91261a259a6dd2f425b3b060c868dc2a2e
- annotation multiple submit bug fixed and axes added in 747b2f5cd189fe947f90064bc9d5f9b1e53a404d

**Comment by atruskie** [comment]
- layout and landing list, and about, pages cleaned up in 7aef81e930b8c926cd53628af9ae0342a10352f1
- media tracking, live audio, axes linked from sites to trials in e5b55868301138c8960315b27b4c95ce44ec1baa

**Comment by atruskie** [comment]
- continue button done in a63427ac29160c78fdf249cb14b996797e10d845
- annotorious canvas scale bug in 0e986bda85116311b12122c2ac9e6c5f856f8c90

**Comment by Allcharles** [comment]
- Audio position tracker commits
  - e5bab4891e829918febc24f4fc2c8c7019adf63a
  - 4583c2406d48925101f614507494925092de1d03
  - 00b66bbe4da380c1983e9b9f9e993466d10f8132
  - c3d7a82843bb9a5c68d58a76926c03cf49293a6f
  - 6f3f0143e9b2da71df969a938ffad341d594d5de
